CREATE TABLE live_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room VARCHAR(100),
  user_id INT,
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE `live_messages` ADD `type` VARCHAR(50) NULL DEFAULT NULL AFTER `user_id`;
ALTER TABLE `live_messages` ADD `name` VARCHAR(50) NULL DEFAULT NULL AFTER `room`;
ALTER TABLE live_messages 
ADD COLUMN is_read TINYINT(1) DEFAULT 0;